services:

  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.15.1
    container_name: mlflow-server

    working_dir: /app

    volumes:
      - ./mlflow.db:/app/mlflow.db
      - ./mlartifacts:/app/mlartifacts
      - ./mlruns:/app/mlruns

    ports:
      - "5001:5000"

    command: >
      mlflow server
      --backend-store-uri sqlite:////app/mlflow.db
      --default-artifact-root /app/mlartifacts
      --host 0.0.0.0
      --port 5000
      --allowed-hosts "localhost:*,127.0.0.1:*,mlflow:*,host.docker.internal:*"

    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:5000/health')"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s


  api:
    image: ghcr.io/yash-bhinwal/cifar10-api:latest
    container_name: cifar10-api

    depends_on:
      mlflow:
        condition: service_healthy

    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000

    ports:
      - "8000:8000"